### ISSUE TITLE
Issue with ggplot2 3.4.0

### ISSUE THREAD

**Issue by thomasp85** [YuLab-SMU/shinyTempSignal#20]
Hi

We recently released ggplot2 3.4.0 and while we didn’t detect issues with cocktailApp during our tests, CRAN has seen issues after release. This mail is to notify you about this and offer help if there are any issues you have trouble fixing

Kind regards
Thomas Lin Pedersen, ggplot2 maintainer

**Comment by jmirobla** [comment]
Hi [thomasp85](https://github.com/thomasp85) and [GuangchuangYu](https://github.com/GuangchuangYu),
I've been using the `cnetplot()` function from `enrichplot` package, which plot a data network and worked fine with ggplo2 version 3.3.6, once I updated to version 3.4, the ggplot2 object did not plot the network because a problem re-scaling when `cnetplot()` is using internally the dependency `ggnewscale` package. After getting back to ggplot2 version 3.3.6 the problem disappeared. Hope you can fix this issue in the new release.

Many thanks
